import React from 'react';
import { IIconTypes } from '~/utils/types';
import { DEPARTMENTS, ROLES } from '~/hooks/role';
import TopNav from '~/views/app/home/top-nav';
import { Href } from 'expo-router';

export interface IAppRoute {
    href: Href;
    name: string;
    options: any;
    submenus: IAppRoute[] | [];
    users: (ROLES | DEPARTMENTS)[];
    inMenuBar: boolean;
    inMore: boolean;
    hideHeader?: boolean;
    customHeader?: React.FC<any>;
    icon: { name: string; type: IIconTypes };
}

const AppRoutes: IAppRoute[] = [
    {
        name: 'Home',
        href: '/(tabs)',
        options: { title: 'Home' },
        submenus: [],
        users: [],
        inMenuBar: true,
        inMore: false,
        customHeader: TopNav,
        icon: { name: 'home', type: 'antdesign' },
    },
    {
        name: 'Attendance',
        options: { title: 'Attendance' },
        submenus: [],
        users: [],
        inMenuBar: true,
        inMore: false,
        icon: { name: 'checklist', type: 'octicon' },
    },
    {
        name: 'Permissions',
        options: { title: 'Permissions' },
        submenus: [
            {
                name: 'Request permission',
                options: { title: 'Request permission' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'hand-left-outline', type: 'ionicon' },
            },
            {
                name: 'Permission Details',
                options: { title: 'Permission Details' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'hand-left-outline', type: 'ionicon' },
            },
        ],
        users: [],
        inMenuBar: true,
        inMore: false,
        icon: { name: 'hand-left-outline', type: 'ionicon' },
    },
    {
        name: 'Tickets',
        options: { title: 'Tickets' },
        submenus: [
            {
                name: 'Ticket Details',
                options: { title: 'Ticket Details' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: {
                    name: 'ticket-confirmation-outline',
                    type: 'material-community',
                },
            },
            {
                name: 'Issue Ticket',
                options: { title: 'Issue Ticket' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: {
                    name: 'ticket-confirmation-outline',
                    type: 'material-community',
                },
            },
        ],
        users: [],
        inMenuBar: true,
        inMore: false,
        icon: {
            name: 'ticket-confirmation-outline',
            type: 'material-community',
        },
    },
    {
        name: 'Notifications',
        options: { title: 'Notifications' },
        submenus: [],
        users: [],
        inMenuBar: false,
        inMore: false,
        icon: { name: 'notifications-outline', type: 'ionicon' },
    },
    {
        name: 'Profile',
        options: { title: 'Profile' },
        submenus: [
            {
                name: 'Edit Profile',
                options: { title: 'Edit Profile' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person-outline', type: 'ionicon' },
            },
        ],
        users: [],
        inMenuBar: false,
        inMore: false,
        icon: { name: 'person-outline', type: 'ionicon' },
    },
    {
        name: 'Reports',
        options: { title: 'Reports' },
        submenus: [
            {
                name: 'Childcare Report',
                options: { title: 'Childcare Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
            },
            {
                name: 'Incident Report',
                options: { title: 'Incident Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
            },
            {
                name: 'Attendance Report',
                options: { title: 'Attendance Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
            },
            {
                name: 'Guest Report',
                options: { title: 'Guest Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
            },
            {
                name: 'Service Report',
                options: { title: 'Service Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
            },
            {
                name: 'Security Report',
                options: { title: 'Security Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
            },
            {
                name: 'Transfer Report',
                options: { title: 'Transfer Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
            },
            {
                name: 'Campus Report',
                options: { title: 'Campus Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
            },
        ],
        users: [
            ROLES.HOD,
            ROLES.AHOD,
            ROLES.groupHead,
            ROLES.campusPastor,
            ROLES.globalPastor,
            ROLES.campusCoordinator,
        ],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'graph', type: 'octicon' },
    },
    {
        name: 'Service management',
        options: { title: 'Service management' },
        submenus: [
            {
                name: 'Create service',
                options: { title: 'Create service' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'church', type: 'material-community' },
            },
            {
                name: 'Create CGWC session',
                options: { title: 'Create CGWC Session' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'church', type: 'material-community' },
            },
        ],
        users: [ROLES.superAdmin],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'church', type: 'material-community' },
    },
    {
        name: 'Assign Group Head',
        options: { title: 'Assign Group Head' },
        submenus: [],
        users: [ROLES.superAdmin, ROLES.globalPastor],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'account-group-outline', type: 'material-community' },
    },
    {
        name: 'Group Head Campus',
        options: { title: 'Group Head Campus' },
        submenus: [
            {
                name: 'Group Head Campuses',
                options: { title: 'Group Head Campuses' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
            {
                name: 'Group Head Departments',
                options: { title: 'Group Head Departments' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
            {
                name: 'Group Head Department Activities',
                options: { title: 'Group Head Department Activities' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
        ],
        users: [ROLES.groupHead],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'home-group', type: 'material-community' },
    },
    {
        name: 'GH Reports History',
        options: { title: 'GH Reports History' },
        submenus: [],
        users: [ROLES.groupHead],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'graph', type: 'octicon' },
    },
    {
        name: 'Group Head Service Report',
        options: { title: 'Group Head Service Report' },
        submenus: [
            {
                name: 'Group Head Service Summary',
                options: { title: 'Group Head Service Summary' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },

            {
                name: 'Submit report summary',
                options: { title: 'Submit report summary' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
        ],
        users: [ROLES.groupHead, ROLES.campusPastor],
        inMenuBar: false,
        inMore: false,
        icon: { name: 'graph', type: 'octicon' },
    },
    {
        name: 'Workforce summary',
        options: { title: 'Workforce management' },
        submenus: [
            {
                name: 'Workforce management',
                options: { title: 'Workforce management' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
            {
                name: 'User Profile',
                options: { title: 'User profile' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
            {
                name: 'User Report',
                options: { title: 'User report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
            {
                name: 'User Report Details',
                options: { title: 'User report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
            {
                name: 'Create User',
                options: { title: 'Create user' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
            {
                name: 'Create Department',
                options: { title: 'Create department' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
            {
                name: 'Create Campus',
                options: { title: 'Create campus' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
            {
                name: 'Campus workforce',
                options: { title: 'Campus workforce' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
            {
                name: 'Global workforce',
                options: { title: 'Global workforce' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
            },
        ],
        users: [
            ROLES.HOD,
            ROLES.AHOD,
            DEPARTMENTS.ME,
            DEPARTMENTS.QC,
            ROLES.groupHead,
            ROLES.superAdmin,
            ROLES.globalAdmin,
            ROLES.campusPastor,
            ROLES.globalPastor,
            ROLES.campusCoordinator,
        ],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'database-cog-outline', type: 'material-community' },
    },
    {
        name: 'Manual clock in',
        options: { title: 'Manual clock in' },
        submenus: [],
        users: [ROLES.superAdmin, ROLES.campusPastor, DEPARTMENTS.QC, DEPARTMENTS.ME, ROLES.campusCoordinator],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'timer-outline', type: 'material-community' },
    },
    {
        name: 'Export Data',
        options: { title: 'Export Data' },
        submenus: [],
        users: [
            DEPARTMENTS.QC,
            DEPARTMENTS.ME,
            ROLES.groupHead,
            ROLES.superAdmin,
            ROLES.globalAdmin,
            ROLES.campusPastor,
            ROLES.globalPastor,
            ROLES.campusCoordinator,
        ],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'download-outline', type: 'ionicon' },
    },

    {
        name: 'CGLS',
        options: { title: 'CGLS' },
        submenus: [
            {
                name: 'Create CGWC',
                options: { title: 'Create CGWC' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'crown', type: 'foundation' },
            },
            {
                name: 'CGWC Details',
                options: { title: 'CGWC Details' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                hideHeader: true,
                customHeader: TopNav,
                icon: { name: 'crown', type: 'foundation' },
            },
            {
                name: 'Create Instant Message',
                options: { title: 'Create Instant Message' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'new-message', type: 'entypo' },
            },
            {
                name: 'CGWC Report',
                options: { title: 'CGWC Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'crown', type: 'foundation' },
            },
            {
                name: 'CGWC Attendance',
                options: { title: 'CGWC Attendance' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'ionicon' },
            },
            {
                name: 'CGWC Resources',
                options: { title: 'CGWC Resources' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'ionicon' },
            },
            {
                name: 'CGWC Feedback',
                options: { title: 'CGWC Feedback' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'ionicon' },
            },
        ],
        users: [],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'crown', type: 'foundation' },
    },

    {
        name: 'More',
        options: { title: 'More' },
        submenus: [],
        users: [],
        inMenuBar: true,
        inMore: false,
        icon: { name: 'menu-outline', type: 'ionicon' },
    },
];

const AuthRoutes: Omit<IAppRoute, 'icon'>[] = [
    {
        name: 'Welcome',
        options: { title: 'Welcome' },
        submenus: [],
        users: [],
        inMore: false,
        inMenuBar: false,
    },
    {
        name: 'Verify Email',
        options: { title: 'Verify Email' },
        submenus: [],
        users: [],
        inMore: false,
        inMenuBar: false,
    },
    {
        name: 'Login',
        options: { title: 'Login' },
        submenus: [],
        users: [],
        inMore: false,
        inMenuBar: false,
    },
    {
        name: 'Register',
        options: { title: 'Register' },
        submenus: [],
        users: [],
        inMore: false,
        inMenuBar: false,
    },
    {
        name: 'Forgot Password',
        options: { title: 'Forgot Password' },
        submenus: [],
        users: [],
        inMore: false,
        inMenuBar: false,
    },
    {
        name: 'Reset Password',
        options: { title: 'Reset Password' },
        submenus: [],
        users: [],
        inMore: false,
        inMenuBar: false,
    },
];

export { AppRoutes, AuthRoutes };
