import { IIconTypes } from '~/utils/types';
import { DEPARTMENTS, ROLES } from '~/hooks/role';
import { Href } from 'expo-router';

export interface IAppRoute {
    href: Href | any; // TODO: Remove `any` type after creating all routes.
    name: string;
    options: any;
    submenus: IAppRoute[] | [];
    users: (ROLES | DEPARTMENTS)[];
    inMenuBar: boolean;
    inMore: boolean;
    hideHeader?: boolean;
    icon: { name: string; type: IIconTypes };
}

const AppRoutes: IAppRoute[] = [
    {
        name: 'Home',
        href: '/',
        options: { title: 'Home' },
        submenus: [],
        users: [],
        inMenuBar: true,
        inMore: false,
        icon: { name: 'home', type: 'antdesign' },
    },
    {
        name: 'Attendance',
        options: { title: 'Attendance' },
        submenus: [],
        users: [],
        inMenuBar: true,
        inMore: false,
        icon: { name: 'checklist', type: 'octicon' },
        href: '/attendance',
    },
    {
        name: 'Permissions',
        options: { title: 'Permissions' },
        submenus: [
            {
                name: 'Request permission',
                options: { title: 'Request permission' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'hand-left-outline', type: 'ionicon' },
                href: '/permissions/request-permission',
            },
            {
                name: 'Permission Details',
                options: { title: 'Permission Details' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'hand-left-outline', type: 'ionicon' },
                href: '/permissions/permission-details',
            },
        ],
        users: [],
        inMenuBar: true,
        inMore: false,
        icon: { name: 'hand-left-outline', type: 'ionicon' },
        href: '/permissions',
    },
    {
        name: 'Tickets',
        options: { title: 'Tickets' },
        submenus: [
            {
                name: 'Ticket Details',
                options: { title: 'Ticket Details' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'ticket-confirmation-outline', type: 'material-community' },
                href: '/tickets/ticket-details',
            },
            {
                name: 'Issue Ticket',
                options: { title: 'Issue Ticket' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'ticket-confirmation-outline', type: 'material-community' },
                href: '/tickets/issue-ticket',
            },
        ],
        users: [],
        inMenuBar: true,
        inMore: false,
        icon: { name: 'ticket-confirmation-outline', type: 'material-community' },
        href: '/tickets',
    },
    {
        name: 'Notifications',
        options: { title: 'Notifications' },
        submenus: [],
        users: [],
        inMenuBar: false,
        inMore: false,
        icon: { name: 'notifications-outline', type: 'ionicon' },
        href: '/notifications',
    },
    {
        name: 'Profile',
        options: { title: 'Profile' },
        submenus: [
            {
                name: 'Edit Profile',
                options: { title: 'Edit Profile' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person-outline', type: 'ionicon' },
                href: '/profile/edit-profile',
            },
        ],
        users: [],
        inMenuBar: false,
        inMore: false,
        icon: { name: 'person-outline', type: 'ionicon' },
        href: '/profile',
    },
    {
        name: 'Reports',
        options: { title: 'Reports' },
        submenus: [
            {
                name: 'Childcare Report',
                options: { title: 'Childcare Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
                href: '/reports/childcare-report',
            },
            {
                name: 'Incident Report',
                options: { title: 'Incident Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
                href: '/reports/incident-report',
            },
            {
                name: 'Attendance Report',
                options: { title: 'Attendance Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
                href: '/reports/attendance-report',
            },
            {
                name: 'Guest Report',
                options: { title: 'Guest Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
                href: '/reports/guest-report',
            },
            {
                name: 'Service Report',
                options: { title: 'Service Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
                href: '/reports/service-report',
            },
            {
                name: 'Security Report',
                options: { title: 'Security Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
                href: '/reports/security-report',
            },
            {
                name: 'Transfer Report',
                options: { title: 'Transfer Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
                href: '/reports/transfer-report',
            },
            {
                name: 'Campus Report',
                options: { title: 'Campus Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'graph', type: 'octicon' },
                href: '/reports/campus-report',
            },
        ],
        users: [
            ROLES.HOD,
            ROLES.AHOD,
            ROLES.groupHead,
            ROLES.campusPastor,
            ROLES.globalPastor,
            ROLES.campusCoordinator,
        ],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'graph', type: 'octicon' },
        href: '/reports',
    },
    {
        name: 'Service management',
        options: { title: 'Service management' },
        submenus: [
            {
                name: 'Create service',
                options: { title: 'Create service' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'church', type: 'material-community' },
                href: '/service-management/create-service',
            },
            {
                name: 'Create CGWC session',
                options: { title: 'Create CGWC Session' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'church', type: 'material-community' },
                href: '/service-management/create-cgwc-session',
            },
        ],
        users: [ROLES.superAdmin],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'church', type: 'material-community' },
        href: '/service-management',
    },
    {
        name: 'Assign Group Head',
        options: { title: 'Assign Group Head' },
        submenus: [],
        users: [ROLES.superAdmin, ROLES.globalPastor],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'account-group-outline', type: 'material-community' },
        href: '/assign-group-head',
    },
    {
        name: 'Group Head Campus',
        options: { title: 'Group Head Campus' },
        submenus: [
            {
                name: 'Group Head Campuses',
                options: { title: 'Group Head Campuses' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/group-head-campus/group-head-campuses',
            },
            {
                name: 'Group Head Departments',
                options: { title: 'Group Head Departments' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/group-head-campus/group-head-departments',
            },
            {
                name: 'Group Head Department Activities',
                options: { title: 'Group Head Department Activities' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/group-head-campus/group-head-department-activities',
            },
        ],
        users: [ROLES.groupHead],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'home-group', type: 'material-community' },
        href: '/group-head-campus',
    },
    {
        name: 'GH Reports History',
        options: { title: 'GH Reports History' },
        submenus: [],
        users: [ROLES.groupHead],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'graph', type: 'octicon' },
        href: '/gh-reports-history',
    },
    {
        name: 'Group Head Service Report',
        options: { title: 'Group Head Service Report' },
        submenus: [
            {
                name: 'Group Head Service Summary',
                options: { title: 'Group Head Service Summary' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/group-head-service-report/group-head-service-summary',
            },
            {
                name: 'Submit report summary',
                options: { title: 'Submit report summary' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/group-head-service-report/submit-report-summary',
            },
        ],
        users: [ROLES.groupHead, ROLES.campusPastor],
        inMenuBar: false,
        inMore: false,
        icon: { name: 'graph', type: 'octicon' },
        href: '/group-head-service-report',
    },
    {
        name: 'Workforce summary',
        options: { title: 'Workforce management' },
        submenus: [
            {
                name: 'Workforce management',
                options: { title: 'Workforce management' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/workforce-summary/workforce-management',
            },
            {
                name: 'User Profile',
                options: { title: 'User profile' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/workforce-summary/user-profile',
            },
            {
                name: 'User Report',
                options: { title: 'User report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/workforce-summary/user-report',
            },
            {
                name: 'User Report Details',
                options: { title: 'User report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/workforce-summary/user-report-details',
            },
            {
                name: 'Create User',
                options: { title: 'Create user' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/workforce-summary/create-user',
            },
            {
                name: 'Create Department',
                options: { title: 'Create department' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/workforce-summary/create-department',
            },
            {
                name: 'Create Campus',
                options: { title: 'Create campus' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/workforce-summary/create-campus',
            },
            {
                name: 'Campus workforce',
                options: { title: 'Campus workforce' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/workforce-summary/campus-workforce',
            },
            {
                name: 'Global workforce',
                options: { title: 'Global workforce' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'octicon' },
                href: '/workforce-summary/global-workforce',
            },
        ],
        users: [
            ROLES.HOD,
            ROLES.AHOD,
            DEPARTMENTS.ME,
            DEPARTMENTS.QC,
            ROLES.groupHead,
            ROLES.superAdmin,
            ROLES.globalAdmin,
            ROLES.campusPastor,
            ROLES.globalPastor,
            ROLES.campusCoordinator,
        ],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'database-cog-outline', type: 'material-community' },
        href: '/workforce-summary',
    },
    {
        name: 'Manual clock in',
        options: { title: 'Manual clock in' },
        submenus: [],
        users: [ROLES.superAdmin, ROLES.campusPastor, DEPARTMENTS.QC, DEPARTMENTS.ME, ROLES.campusCoordinator],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'timer-outline', type: 'material-community' },
        href: '/manual-clock-in',
    },
    {
        name: 'Export Data',
        options: { title: 'Export Data' },
        submenus: [],
        users: [
            DEPARTMENTS.QC,
            DEPARTMENTS.ME,
            ROLES.groupHead,
            ROLES.superAdmin,
            ROLES.globalAdmin,
            ROLES.campusPastor,
            ROLES.globalPastor,
            ROLES.campusCoordinator,
        ],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'download-outline', type: 'ionicon' },
        href: '/export-data',
    },
    {
        name: 'CGLS',
        options: { title: 'CGLS' },
        submenus: [
            {
                name: 'Create CGWC',
                options: { title: 'Create CGWC' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'crown', type: 'foundation' },
                href: '/cgwc/create-cgwc',
            },
            {
                name: 'CGWC Details',
                options: { title: 'CGWC Details' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                hideHeader: true,
                icon: { name: 'crown', type: 'foundation' },
                href: '/cgwc/cgwc-details',
            },
            {
                name: 'Create Instant Message',
                options: { title: 'Create Instant Message' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'new-message', type: 'entypo' },
                href: '/cgwc/create-instant-message',
            },
            {
                name: 'CGWC Report',
                options: { title: 'CGWC Report' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'crown', type: 'foundation' },
                href: '/cgwc/cgwc-report',
            },
            {
                name: 'CGWC Attendance',
                options: { title: 'CGWC Attendance' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'ionicon' },
                href: '/cgwc/cgwc-attendance',
            },
            {
                name: 'CGWC Resources',
                options: { title: 'CGWC Resources' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'ionicon' },
                href: '/cgwc/cgwc-resources',
            },
            {
                name: 'CGWC Feedback',
                options: { title: 'CGWC Feedback' },
                submenus: [],
                users: [],
                inMenuBar: false,
                inMore: false,
                icon: { name: 'person', type: 'ionicon' },
                href: '/cgwc/cgwc-feedback',
            },
        ],
        users: [],
        inMenuBar: false,
        inMore: true,
        icon: { name: 'crown', type: 'foundation' },
        href: '/cgls',
    },
    {
        name: 'More',
        options: { title: 'More' },
        submenus: [],
        users: [],
        inMenuBar: true,
        inMore: false,
        icon: { name: 'menu-outline', type: 'ionicon' },
        href: '/more',
    },
];

export { AppRoutes };
