export enum IMGBB_ALBUM_ID {
    PROFILE_PICTURE = 'LnkmtT',
    INCIDENT_REPORT = 'Zd1Wcw',
    DEPARTMENTAL_REPORT = '23rGDQ',
}

export type IImbbAlbumId =
    | IMGBB_ALBUM_ID.DEPARTMENTAL_REPORT
    | IMGBB_ALBUM_ID.INCIDENT_REPORT
    | IMGBB_ALBUM_ID.PROFILE_PICTURE;
